// Shared styles for all components
import { StyleSheet, Platform } from 'react-native';
import { COLORS } from './constants';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.background },
  centerContent: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  loadingText: { color: COLORS.text, fontSize: 16 },

  // Onboarding styles
  onboardingContainer: { flex: 1, backgroundColor: COLORS.background },
  onboardingContent: { flex: 1, justifyContent: 'center', alignItems: 'center', paddingHorizontal: 40 },
  onboardingIcon: { fontSize: 80, marginBottom: 32 },
  onboardingTitle: { fontSize: 28, fontWeight: 'bold', color: COLORS.text, marginBottom: 16, textAlign: 'center' },
  onboardingDescription: { fontSize: 16, color: COLORS.textSecondary, textAlign: 'center', lineHeight: 24 },
  onboardingFooter: { paddingHorizontal: 24, paddingBottom: 40, alignItems: 'center' },
  onboardingDots: { flexDirection: 'row', marginBottom: 24 },
  onboardingDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: COLORS.surfaceLight, marginHorizontal: 4 },
  onboardingDotActive: { backgroundColor: COLORS.primary, width: 24 },
  onboardingButton: { backgroundColor: COLORS.primary, paddingVertical: 16, paddingHorizontal: 48, borderRadius: 12, width: '100%' },
  onboardingButtonText: { color: COLORS.text, fontSize: 18, fontWeight: 'bold', textAlign: 'center' },
  skipButton: { marginTop: 16, padding: 8 },
  skipButtonText: { color: COLORS.textMuted, fontSize: 14 },

  // Permission styles
  permissionContent: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 24 },
  permissionIconContainer: { width: 120, height: 120, borderRadius: 60, backgroundColor: COLORS.surface, justifyContent: 'center', alignItems: 'center', marginBottom: 24 },
  permissionIcon: { fontSize: 56 },
  permissionTitle: { fontSize: 24, fontWeight: 'bold', color: COLORS.text, marginBottom: 12 },
  permissionText: { fontSize: 16, color: COLORS.textSecondary, textAlign: 'center', marginBottom: 8, lineHeight: 24 },
  permissionNote: { fontSize: 14, color: COLORS.textMuted, textAlign: 'center', marginBottom: 32, lineHeight: 20 },
  permissionButton: { backgroundColor: COLORS.primary, paddingVertical: 16, paddingHorizontal: 40, borderRadius: 12 },
  permissionButtonText: { color: COLORS.text, fontSize: 18, fontWeight: 'bold' },

  // Header styles
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 12, paddingTop: Platform.OS === 'android' ? 48 : 12, position: 'absolute', top: 0, left: 0, right: 0, zIndex: 10 },
  headerCenter: { flex: 1, alignItems: 'center', marginHorizontal: 8 },
  headerStatusBadge: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 14, paddingVertical: 8, borderRadius: 20, backgroundColor: 'rgba(26, 44, 34, 0.9)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.15)' },
  headerStatusEmoji: { fontSize: 16, marginRight: 6 },
  headerStatusText: { fontSize: 13, fontWeight: '600', color: COLORS.text },
  headerTitle: { fontSize: 14, fontWeight: '700', color: COLORS.text, letterSpacing: 3, textTransform: 'uppercase' },
  headerButton: { width: 44, height: 44, borderRadius: 22, backgroundColor: 'rgba(26, 44, 34, 0.9)', justifyContent: 'center', alignItems: 'center', borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)' },
  headerButtonIcon: { fontSize: 18 },

  // Stats Bar styles
  statsBar: { position: 'absolute', top: Platform.OS === 'android' ? 48 : 50, left: 12, right: 12, flexDirection: 'row', justifyContent: 'center', alignItems: 'center', backgroundColor: 'rgba(26, 44, 34, 0.9)', borderRadius: 20, paddingVertical: 8, paddingHorizontal: 12, zIndex: 10, borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)' },
  statsBarItem: { flexDirection: 'row', alignItems: 'center', marginHorizontal: 4 },
  statsBarIcon: { fontSize: 12, marginRight: 3 },
  statsBarValue: { fontSize: 12, fontWeight: '600', color: COLORS.text },
  statsBarDivider: { width: 1, height: 16, backgroundColor: 'rgba(255,255,255,0.2)', marginHorizontal: 4 },

  // Camera styles
  cameraContainer: { flex: 1, backgroundColor: '#000' },
  camera: { flex: 1 },
  statusOverlay: { flex: 1, borderWidth: 2, borderRadius: 20, justifyContent: 'space-between', alignItems: 'center', padding: 16 },
  statusBadge: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 20, paddingVertical: 10, borderRadius: 20, backgroundColor: 'rgba(17, 33, 23, 0.7)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.08)' },
  statusEmoji: { fontSize: 18, marginRight: 8 },
  statusText: { fontSize: 12, fontWeight: 'bold', color: COLORS.text },
  sessionInfo: { backgroundColor: 'rgba(17, 33, 23, 0.7)', paddingHorizontal: 20, paddingVertical: 10, borderRadius: 20, alignItems: 'center', flexDirection: 'row', gap: 12, borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)' },
  sessionTimeLabel: { fontSize: 14, color: COLORS.textMuted },
  sessionTime: { fontSize: 12, color: COLORS.text, fontWeight: 'bold', fontFamily: 'monospace' },
  guideOverlay: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: COLORS.overlayStrong },
  guideEmoji: { fontSize: 56, marginBottom: 16 },
  guideText: { fontSize: 18, color: COLORS.text, textAlign: 'center', lineHeight: 26, fontWeight: '500' },
  guideHint: { fontSize: 13, color: COLORS.textMuted, marginTop: 12, textAlign: 'center' },

  // Bottom Panel styles
  bottomPanel: { backgroundColor: 'rgba(26, 44, 34, 0.95)', paddingHorizontal: 16, paddingTop: 10, paddingBottom: 52, borderTopLeftRadius: 24, borderTopRightRadius: 24, borderWidth: 1, borderColor: 'rgba(255,255,255,0.12)', borderBottomWidth: 0 },
  bottomPanelCollapsed: { paddingTop: 6, paddingBottom: 52 },
  panelHandle: { alignItems: 'center', paddingVertical: 8, marginBottom: 2, marginTop: -4 },
  panelHandleBar: { width: 36, height: 4, borderRadius: 2, backgroundColor: 'rgba(255,255,255,0.3)', marginBottom: 2 },
  panelHandleArrow: { fontSize: 10, color: 'rgba(255,255,255,0.4)' },
  toggleRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 8, gap: 8 },
  toggleButton: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(255,255,255,0.05)', borderRadius: 12, paddingVertical: 10, paddingHorizontal: 10, borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)' },
  toggleButtonActive: { backgroundColor: 'rgba(25, 230, 107, 0.15)', borderColor: COLORS.primary },
  toggleIcon: { fontSize: 16, marginRight: 6 },
  toggleLabel: { fontSize: 13, fontWeight: '600', color: COLORS.textSecondary, marginRight: 6 },
  toggleLabelActive: { color: COLORS.text },
  screenOffButtonActive: { backgroundColor: 'rgba(100, 100, 255, 0.15)', borderColor: 'rgba(100, 100, 255, 0.5)' },
  toggleIndicator: { backgroundColor: 'rgba(255,255,255,0.1)', paddingHorizontal: 8, paddingVertical: 3, borderRadius: 8 },
  toggleIndicatorActive: { backgroundColor: COLORS.primary },
  toggleIndicatorText: { fontSize: 10, fontWeight: '700', color: COLORS.text },

  // Pattern quick select styles
  patternQuickSelect: { flexDirection: 'row', alignItems: 'flex-start', marginBottom: 8, backgroundColor: 'rgba(255,255,255,0.03)', borderRadius: 10, paddingHorizontal: 10, paddingVertical: 6 },
  patternQuickLabel: { fontSize: 12, color: COLORS.text, fontWeight: '600', paddingTop: 4, marginRight: 8 },
  patternGrid: { flex: 1, flexDirection: 'row', flexWrap: 'wrap', gap: 4 },
  patternPill: { paddingVertical: 4, paddingHorizontal: 8, borderRadius: 12, backgroundColor: 'rgba(255,255,255,0.08)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)' },
  patternPillActive: { backgroundColor: COLORS.primary, borderColor: COLORS.primary },
  patternPillText: { fontSize: 11, color: COLORS.textSecondary, fontWeight: '600' },
  patternPillTextActive: { color: COLORS.background },

  // Slider styles (inline horizontal layout)
  sliderGroup: { flexDirection: 'row', alignItems: 'center', marginBottom: 8, backgroundColor: 'rgba(255,255,255,0.03)', borderRadius: 10, paddingHorizontal: 10, paddingVertical: 2 },
  sliderGroupDisabled: { opacity: 0.4 },
  sliderLabel: { fontSize: 12, color: COLORS.text, fontWeight: '600' },
  sliderLabelDisabled: { color: COLORS.textMuted },
  sliderValue: { fontSize: 12, color: COLORS.primary, fontWeight: '700', minWidth: 34, textAlign: 'right' },
  sliderValueDisabled: { color: COLORS.textMuted },
  slider: { flex: 1, height: 32, marginHorizontal: 4 },

  // Stop/Start button styles
  stopButton: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(26, 44, 34, 0.8)', paddingVertical: 12, borderRadius: 10, marginTop: 6, borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)' },
  startButton: { backgroundColor: COLORS.primary },
  stopButtonIcon: { fontSize: 14, marginRight: 6 },
  stopButtonText: { fontSize: 13, fontWeight: '700', color: COLORS.text, letterSpacing: 1 },

  // Legacy styles
  statsRow: { flexDirection: 'row', justifyContent: 'space-around', marginBottom: 12, backgroundColor: 'rgba(17, 33, 23, 0.5)', borderRadius: 20, paddingVertical: 10, paddingHorizontal: 16, borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)' },
  statItem: { alignItems: 'center', flexDirection: 'row', gap: 6 },
  statValue: { fontSize: 12, fontWeight: 'bold', color: COLORS.text, fontFamily: 'monospace' },
  statLabel: { fontSize: 14, color: COLORS.textMuted },
  mainButton: { alignItems: 'center', justifyContent: 'center', paddingVertical: 12, borderRadius: 12, marginBottom: 8, flexDirection: 'row', gap: 8, borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)' },
  mainButtonText: { color: COLORS.text, fontSize: 12, fontWeight: 'bold', textTransform: 'uppercase', letterSpacing: 1 },
  sensitivityRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 },
  sensitivityLabel: { fontSize: 14, color: COLORS.textMuted, marginRight: 4 },
  sensButton: { paddingVertical: 6, paddingHorizontal: 14, borderRadius: 8, backgroundColor: 'rgba(17, 33, 23, 0.5)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.08)' },
  sensButtonActive: { backgroundColor: COLORS.primary, borderColor: COLORS.primary },
  sensButtonText: { fontSize: 11, color: COLORS.textSecondary },
  sensButtonTextActive: { color: COLORS.background, fontWeight: 'bold' },
  adContainer: { alignItems: 'center', backgroundColor: COLORS.background, paddingBottom: Platform.OS === 'ios' ? 0 : 8 },

  // Modal styles
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.7)', justifyContent: 'flex-end' },
  modalContent: { backgroundColor: 'rgba(17, 33, 23, 0.95)', borderTopLeftRadius: 24, borderTopRightRadius: 24, maxHeight: '80%', borderWidth: 1, borderColor: 'rgba(255,255,255,0.08)', borderBottomWidth: 0 },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 20, borderBottomWidth: 1, borderBottomColor: 'rgba(255,255,255,0.08)' },
  modalTitle: { fontSize: 20, fontWeight: 'bold', color: COLORS.text },
  modalCloseButton: { width: 40, height: 40, borderRadius: 20, backgroundColor: 'rgba(255,255,255,0.1)', justifyContent: 'center', alignItems: 'center', borderWidth: 1, borderColor: 'rgba(255,255,255,0.08)' },
  modalCloseText: { fontSize: 16, color: COLORS.textSecondary },
  modalBody: { padding: 20 },

  // Settings styles
  settingsSection: { marginBottom: 24 },
  sectionTitle: { fontSize: 16, fontWeight: 'bold', color: COLORS.text, marginBottom: 4 },
  sectionDescription: { fontSize: 13, color: COLORS.textMuted, marginBottom: 12 },
  sensitivityContainer: { flexDirection: 'row', gap: 8 },
  sensitivityOption: { flex: 1, paddingVertical: 14, paddingHorizontal: 12, borderRadius: 12, backgroundColor: 'rgba(255,255,255,0.05)', alignItems: 'center', borderWidth: 1, borderColor: 'rgba(255,255,255,0.08)' },
  sensitivityOptionActive: { backgroundColor: COLORS.primary, borderColor: COLORS.primary },
  sensitivityLabelActive: { color: COLORS.text },
  sensitivityDesc: { fontSize: 11, color: COLORS.textMuted },
  sensitivityDescActive: { color: COLORS.text, opacity: 0.8 },
  settingsList: { backgroundColor: 'rgba(255,255,255,0.05)', borderRadius: 12, overflow: 'hidden', borderWidth: 1, borderColor: 'rgba(255,255,255,0.08)' },
  settingItem: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 16, borderBottomWidth: 1, borderBottomColor: 'rgba(255,255,255,0.08)' },
  settingItemLast: { borderBottomWidth: 0 },
  settingTextContainer: { flex: 1, marginRight: 12 },
  settingLabel: { fontSize: 15, color: COLORS.text, fontWeight: '500' },
  settingDescription: { fontSize: 12, color: COLORS.textMuted, marginTop: 2 },
  infoButton: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.05)', borderRadius: 12, padding: 16, borderWidth: 1, borderColor: 'rgba(255,255,255,0.08)' },
  infoButtonText: { fontSize: 15, color: COLORS.text },
  infoButtonArrow: { fontSize: 20, color: COLORS.textMuted },
  appInfo: { marginTop: 16, alignItems: 'center' },
  appInfoText: { fontSize: 12, color: COLORS.textMuted },

  // Stats Modal styles
  statsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
  statCard: { width: '47%', backgroundColor: 'rgba(255,255,255,0.05)', borderRadius: 16, padding: 16, borderLeftWidth: 4, borderWidth: 1, borderColor: 'rgba(255,255,255,0.08)' },
  statIcon: { fontSize: 24, marginBottom: 8 },
  statsNote: { marginTop: 20, padding: 16, backgroundColor: 'rgba(255,255,255,0.05)', borderRadius: 12, alignItems: 'center', borderWidth: 1, borderColor: 'rgba(255,255,255,0.08)' },
  statsNoteText: { fontSize: 14, color: COLORS.textSecondary, textAlign: 'center' },

  // WebView overlay
  webViewOverlay: { position: 'absolute', bottom: 0, left: 0, right: 0, padding: 12, alignItems: 'center' },
  issuesContainer: { backgroundColor: COLORS.overlay, paddingHorizontal: 12, paddingVertical: 6, borderRadius: 10, marginTop: 8 },
  issuesText: { fontSize: 12, color: COLORS.text, fontWeight: '500' },
  loadingOverlay: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: COLORS.overlayStrong, justifyContent: 'center', alignItems: 'center' },

  // Result Modal styles
  resultModalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.8)', justifyContent: 'center', alignItems: 'center', padding: 24 },
  resultModalContent: { backgroundColor: 'rgba(17, 33, 23, 0.95)', borderRadius: 24, padding: 32, alignItems: 'center', width: '100%', maxWidth: 320, borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)' },
  resultEmoji: { fontSize: 64, marginBottom: 16 },
  resultTitle: { fontSize: 24, fontWeight: 'bold', color: COLORS.text, marginBottom: 24 },
  resultStats: { width: '100%', marginBottom: 20 },
  resultStatRow: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: COLORS.border },
  resultStatLabel: { fontSize: 16, color: COLORS.textSecondary },
  resultStatValue: { fontSize: 18, fontWeight: 'bold', color: COLORS.text },
  resultMessage: { fontSize: 14, color: COLORS.textSecondary, textAlign: 'center', marginBottom: 24 },
  resultCloseButton: { backgroundColor: COLORS.primary, paddingVertical: 14, paddingHorizontal: 48, borderRadius: 12 },
  resultCloseButtonText: { color: COLORS.text, fontSize: 16, fontWeight: 'bold' },

  // Pattern selector styles
  patternSection: { paddingHorizontal: 16, paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: 'rgba(255,255,255,0.08)' },
  patternTitle: { fontSize: 13, color: COLORS.textMuted, marginBottom: 8 },
  patternContainer: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  patternOption: { paddingVertical: 8, paddingHorizontal: 14, borderRadius: 8, backgroundColor: 'rgba(255,255,255,0.05)', minWidth: 60, alignItems: 'center', borderWidth: 1, borderColor: 'rgba(255,255,255,0.08)' },
  patternOptionActive: { backgroundColor: COLORS.primary, borderColor: COLORS.primary },
  patternLabel: { fontSize: 12, color: COLORS.textSecondary, fontWeight: '500' },
  patternLabelActive: { color: COLORS.text },

  // Intensity selector styles
  intensityContainer: { marginBottom: 8 },
  intensityLabel: { fontSize: 13, color: COLORS.textMuted, marginBottom: 8 },
  intensityButtons: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  intensityButton: { paddingVertical: 8, paddingHorizontal: 12, borderRadius: 8, backgroundColor: 'rgba(255,255,255,0.05)', minWidth: 44, alignItems: 'center', borderWidth: 1, borderColor: 'rgba(255,255,255,0.08)' },
  intensityButtonActive: { backgroundColor: COLORS.primary, borderColor: COLORS.primary },
  intensityButtonText: { fontSize: 12, color: COLORS.textSecondary, fontWeight: '600' },
  intensityButtonTextActive: { color: COLORS.text },
  intensityHint: { fontSize: 11, color: COLORS.textMuted, marginTop: 6, textAlign: 'center' },

  // Screen Off Mode styles
  screenOffOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#000',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 5,
  },
  screenOffTime: { fontSize: 36, fontWeight: '700', color: COLORS.primary, fontFamily: 'monospace', marginBottom: 24 },
  screenOffHint: { fontSize: 13, color: 'rgba(255,255,255,0.25)' },
  screenOffFullOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#000',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 100,
  },
  screenOffToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  screenOffToggleActive: {
    backgroundColor: 'rgba(100, 100, 255, 0.15)',
    borderColor: 'rgba(100, 100, 255, 0.5)',
  },
  screenOffToggleIcon: { fontSize: 14, marginRight: 6 },
  screenOffToggleLabel: { fontSize: 12, fontWeight: '600', color: COLORS.textSecondary, marginRight: 6 },

  // Toast styles
  toastContainer: {
    position: 'absolute',
    bottom: 120,
    left: 20,
    right: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(26, 44, 34, 0.95)',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 16,
    zIndex: 50,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.15)',
  },
  toastText: { fontSize: 13, color: COLORS.text, fontWeight: '500' },
  toastAction: { fontSize: 13, color: COLORS.primary, fontWeight: '700' },

  // Flash overlay
  flashOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(255, 100, 100, 0.9)',
    zIndex: 9999,
  },

  // Background mode indicator
  backgroundModeIndicator: {
    position: 'absolute',
    top: Platform.OS === 'android' ? 60 : 50,
    right: 10,
    backgroundColor: 'rgba(25, 230, 107, 0.9)',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  backgroundModeText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: 'bold',
  },

  // Landscape layout
  landscapeWrapper: { flex: 1, flexDirection: 'row' },
  statsBarLandscape: { top: 8, left: 8, right: 8, paddingVertical: 6, paddingHorizontal: 10 },
  sidePanel: {
    flex: 0.4,
    backgroundColor: 'rgba(26, 44, 34, 0.95)',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderTopLeftRadius: 24,
    borderBottomLeftRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    borderRightWidth: 0,
  },
});
